### ISSUE TITLE
Easy Mode instructions

### ISSUE THREAD

**Issue by andiohn** [debloper/piosk#21]
Easy Mode: 
1. set pi to book from USB
2. hold shift to start the network installer
3. When booted, plug in USB stick
4. choose 32bit
5. modify the settings before apply
6. success

**Comment by debloper** [comment]
Interesting... will add the [network install](https://www.raspberrypi.com/documentation/computers/getting-started.html#install-over-the-network) as supported option to the docs.

Working on a full-blown [mdbook](https://rust-lang.github.io/mdBook/) based docs pages (instead of overloading the README). This will be included in it.

Thanks for the suggestion!
