### ISSUE TITLE
New splash screen for multi tab and slidebar selection

### ISSUE THREAD

**Issue by marcoemanuelecocco** [debloper/piosk#45]
below is a single page to select in pkiosh at the address http://127.0.0.1/start.html 
the two files are to be placed in the pkiosk/web folder 
in the siteButtons.txt file there are the sites paired with the selection buttons.
[splash screen for Kiosh.zip](https://github.com/user-attachments/files/17308955/splash.screen.for.Kiosh.zip)

**Comment by debloper** [comment]
Are you trying to contribute code?

If so, then please send a [pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests).

Because of security reasons, I'll refrain from opening arbitrary zip file on my system. Please avoid sending code/contributions that way.

If you're new to GitHub, and aren't familiar with the ropes, please do not be discouraged by this. I appreciate your gesture; just can't accept it because of the form it has been presented with.
